### ISSUE TITLE
Stack and cabal-macosx visibility issue

### ISSUE THREAD

**Issue by dimecon** [HeinrichApfelmus/reactive-banana#116]
I'm not sure if this is a problem with stack, if I'm using stack incorrectly, if this is a problem with reactive-banana-wx, or something else. I'm trying to set up a reactive-banana-wx project with stack. When I try to build it, I get the following error.

    /tmp/stack5137/reactive-banana-wx-1.0.0.0/Setup.hs:5:8:
    Could not find module ‘Distribution.MacOSX’
    Perhaps you meant
      Distribution.Make (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
      Distribution.GetOpt
      Distribution.Package (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
    Use -v to see a list of the files searched for.

I don't see why this is. `stack exec ghc-pkg list` shows cabal-macosx-0.2.3.1 in .stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb, and `stack exec ghc-pkg describe cabal-macosx` lists Distribution.MacOSX as an exposed module.

**Comment by HeinrichApfelmus** [comment]
This is probably a problem with the `stack` utility, you may want to open an issue there.

The problem here is that the `cabal-macosx` package has to be in scope when *configuring* the `reactive-banana-wx` library — it uses a custom `Setup.hs` script that also depends on the `cabal-macosx` package. It looks like `stack` cannot deal with this situation yet.

If have no idea if it works, but the following command could be a workaround:

    stack exec stack -- build

The idea is that `stack exec` brings the `cabal-macosx` package into scope for the `stack` util to build the library. But as said, no idea if it works.

**Comment by dimecon** [comment]
Alright, I opened an issue there. `stack exec stack -- build` has the same issue.

**Comment by HeinrichApfelmus** [comment]
Issue #129 suggests a stack.yml file that seems to fix the problem. Does that work?

**Comment by dimecon** [comment]
Yes, simply adding

```
explicit-setup-deps:
    "reactive-banana-wx": true
    entropy: false
```

in particular to `stack.yaml` fixes the problem.
