### ISSUE TITLE
Combinators `switchE` and `switchB` need to be in the `Moment` monad

### ISSUE THREAD

**Issue by atzeus** [HeinrichApfelmus/reactive-banana#119]
Hi Heinrich!

I have a question about switchE & switchB: It seems to me that to implement these you must always remember the last event occurance of an event: at any point in time one might say switchE on some event, the next event in the sequence is then the first occurance of the last event that occured. Is it true that reactive banana retain the last event of all event streams? Can that be a potential source of space leaks? Thanks!!

**Comment by atzeus** [comment]
Also, why is stepper in the moment monad, but switchB not?

**Comment by HeinrichApfelmus** [comment]
> Also, why is stepper in the moment monad, but switchB not?

Oh. That looks like serious issue, thank you! It's possible to express `stepper` in terms of `switchB` as follows

    stepper x e = switchB (pure x) (pure <$> e)

so the latter needs to be in the `Moment` monad as well.

> It seems to me that to implement these you must always remember the last event occurrence of an event: at any point in time one might say switchE on some event, the next event in the sequence is then the first occurrence of the last event that occurred.

I'm afraid, I don't quite understand what you mean. Could you illustrate this with a concrete example, maybe using the semantics for `switchE` from the latest Haddock documentation?

I'm not sure if that's what you mean, but the way `switchE` works is that it only acts as a "gatekeeper": When the "outer" event changes, the "inner" event will be switched, but no new occurrence happens in the output when doing that.

That said, it looks like `switchE` needs to be in the `Moment` monad as well, because it is sensitive to its starting time. More precisely: If we define an operation that discards all occurrences before a particular time (the "starting time"),

    trimE time e = [(t,x) | (t,x) <- e, time <= t]

then it seems to me that

    trimeE t (switchE e) ≠ trimE t (switchE (trimeE t e))

This is an indication that `switchE` needs to be in the `Moment` monad (which essentially supplies the starting time `t`).

**Comment by atzeus** [comment]
This exactly what I meant, sorry for the hastily written message :) 

switchE and switchB need to be in the Moment monad, because they are not "forgetful"

**Comment by atzeus** [comment]
A function f :: Event a -> Event b  is forgetful if:

forall t. f (trimE t x) = timeE t (f x)

A similar thing can be defined for behaviors, which then gives rise to a logical relation as in my Principled Practical FRP paper.

**Comment by HeinrichApfelmus** [comment]
Thanks again for your report. It should be all fixed, now.
