### ISSUE TITLE
Add primitive: plan :: MonadMoment m => Event (m a) -> m (Event a)?

### ISSUE THREAD

**Issue by atzeus** [HeinrichApfelmus/reactive-banana#122]
I'm missing a impure variant of observeE in Reactive banana. I'm proposing a primitive:

```haskell
plan :: MonadMoment m => Event (m a) -> m (Event a)
```
The idea is that after the plan, each time an event occurs in the input event, the action (of type m a) is executed an its result is available though the output event.

Example application: suppose we have an application which uses a network connection. Through a settings menu, the user can select the source of the network connection (for instance different ports). The above combinator can then be used to create a new network connection every time the user enters a port number, and all these network connections can be seen as a single connection via switchE.

Thoughts? Other ways of achieving this?

**Comment by archaephyrryx** [comment]
Is `Reactive.Banana.Frameworks (reactimate)` at all close to what you are looking for? Not sure whether it meets your criterion.

**Comment by atzeus** [comment]
It's related, but reactimate is not as powerful as the combinator i'm proposing. I think you can implement reactimate in terms of plan, but not vice versa.

**Comment by ocharles** [comment]
This kind of stuff is usually done with switching and `execute` (which is almost exactly the type you're looking for, but constrained to `MomentIO`).

**Comment by atzeus** [comment]
I somehow missed execute, thanks! Constrained to MomentIO is not an issue for me.

**Comment by HeinrichApfelmus** [comment]
This combinator can essentially be expressed in terms of existing functions.

As @ocharles mentions, there is

    execute :: Event (MomentIO a) -> MomentIO (Event a)

It has the nice property that the result Event occurs simultaneously with the input event. This combinator is very useful for, say, creating new widgets and registering `AddHandler`s on the fly. The drawback is that the IO that can be done here is very limited.

If you expect that the result Event happens later than the input event, then you can use `reactimate`, `newAddHandler` and `fromAddHandler` in the following combination:

    plan :: Event (IO a) -> MomentIO (Event a)
    plan eIn = do
        (eOut, handler) <- newEvent
        reactimate $ (handler =<<) <$> eIn
        return eOut

Of course, there is still the question of "how late?" does this Event happen with respect to the input, and in which order to several incovations of `plan` executed their IO actions. Since `reatimate` are executed in declaration order, there is at least some information about ordering here, even though the library can't give much guarantees here.


Since an instance `m` of the `MonadMoment` class can have arbitrary effects, I don't think it's possible to use `m` in a contravariant position.
