### ISSUE TITLE
Stateful reactimate and Accessing behavior's new value

### ISSUE THREAD

**Issue by lspitzner** [HeinrichApfelmus/reactive-banana#141]
While making an attempt to provide a bananacific interface for `brick` I ran into two issues/use-cases/questions that I'd like your feedback on. I will link to the relevant bits in the current implementation below; if you are interested [this is the full draft of the interface implementation](https://github.com/jtdaugherty/brick/pull/85/commits/257ceb5578610055a84ebca36495c7864da5ed0b)(includes a rather simple example application.)

1) Is there a "proper" way to handle the following scenario: I have some stateful action `::s -> IO s`, some initial state `::s` and some `::Event ()`. I'd like to execute the action whenever the event fires, updating the "current" state.

My current solution involves an `IORef` to save the state, which I find rather ugly.
[Relevant lines in the brick interface](https://github.com/lspitzner/brick/blob/257ceb5578610055a84ebca36495c7864da5ed0b/src/Brick/MainBanana.hs#L130-L136)

Some thoughts around this:

- I assume the proper way involves a `Behavior` capturing the state
- Not using any IORef, judging simply by types, I can only see two ways to get `s` from `IO s` into `Behavior s`: 
    1. `execute` + `switchB`
    2. `newEvent` + `stepper` with `action >>= behaviourEventH`.
- The first approach does not work (and probably is not supposed to) for the reasons already listed on the `execute` docs (and yes, I tried anyways..).
- The second involves a separate event, leading to worse performance (probably insignificant) but more importantly making the executing non-atomic. If I understand banana semantics correctly, it would be entirely possible that two threads fire the first event nearly simultaneously in a way that results in a destructive update of the state.

#122 is somewhat related.

2) When I have an `e :: Event a`, `f :: a -> b -> b`, `g :: a -> c -> c`, `b :: Behavior b`, `c::Behavior c`, where the behaviors are some `accumB` over `e` via `f`/`g`. Is there any way to `reactimate` some action depending on `e` and the _updated_ values of `b` and `c` in the same instant, without calculating `f` and `g` twice? 

[My current solution in the brick interface](https://github.com/lspitzner/brick/blob/257ceb5578610055a84ebca36495c7864da5ed0b/src/Brick/MainBanana.hs#L112) to this is to drop the "in the same instant" constraint and have some event e' that happens right after e', allowing to access the updated behaviors when e' occurs. This solution works fine in this case, yet I am not completely happy - for other cases I foresee the possibility of running into some equivalent of destructive updates from above (e.g. by some requirement to reactimate each `b`/`c` combo exactly once - which again would clash in some multiple-threads-firing-`e` case).

--

I perhaps should add that the brick-interface as designed in the links seems to work fine already (and performance for this application of banana is noncritical anyways); my questions are more about scaling with more complex use-cases in mind.

**Comment by HeinrichApfelmus** [comment]
1) Well, since an action of type `s -> IO s` can do arbitrary IO, there is no straightforward way to embed it in the event network. The main question is: In which order do we perform the IO, if at all, and how do we specify that?

Unfortunately, there are no pretty answers to this question, hence you will have to live with an ugly one. Using `execute` may work under certain circumstances, but if these circumstances are not met, then the problem is inherently ugly, indeed. Both your original solution and the other one that you've mentioned are valid.

2) Yes, there is a way: the `reactimate'` function (with a prime).

When programming with Events and Behaviors, it is more convenient to use the "old" Behavior values, but when you want to pass the value of a Behavior to the outside world, it is better to use the "new" value. It is perfectly fine to use the `changes` for the latter situation, it was included for this purpose and it is designed to work with `reactimate'`. The `Future` monad may be a bit cumbersome at first, but it indicates that you are dealing with the "new" values, and it prevents you from accidentally using the "new" values.

**Comment by lspitzner** [comment]
Thanks for taking your time to consider and answer to these long questions! It took me a moment to figure out what order you speak of in 1) but I think I got that now (two behaviours could depend on each others new value (via 2) and still pass through IO - so I am effectively asking for the power to create a cyclic dependency through IO.)

But one follow-up question for 2): Am I correctly assuming this solution would require `union` if more than one Behavior is involved, since there will be more than one `Event (Future _)` ? Even if `Future` is `Applicative`, `reactimate'` will require a single `Event` as input(?)

**Comment by HeinrichApfelmus** [comment]
> Thanks for taking your time to consider and answer to these long questions!

My pleasure. :smile:

1) 

> so I am effectively asking for the power to create a cyclic dependency through IO.

Probably, but the issue is more basic: I can't allow arbitrary IO inside `accumB` or other combinators, because the program can contain several Behaviors built in this way, and then it is not at all clear in which order these IO actions are to be performed. Should I update Behavior A first, and then Behavior B, or the other way round? And the trouble is that the order may influence the outcome.

2)

> Am I correctly assuming this solution would require `union`

Yes, you can use `unionWith` on the result of `changes` applied to different Behaviors, but you can also call `reactimate'` several times, one for each Event. It's up to you.

**Comment by lspitzner** [comment]
Regarding 1): But if I have multiple reactimates, the current implementation has no problem to execute them in some (arbitrary?) order, either.. and if the reactimated actions fire events that affect behaviors, the outcome _already_ is arbitrary. That is: I cannot think of an example (with two or more behaviors connected in some way that cause ordering-problems) where your proposed solution would be more deterministic than the arbitrarily-ordered same-instant execution which I wondered about.

**Comment by HeinrichApfelmus** [comment]
> Regarding 1): But if I have multiple reactimates, the current implementation has no problem to execute them in some (arbitrary?) order, either...

Certainly. It's just that whenever you use `reactimate`, the burden of proof is on you to make sure that the order is what you want it is. In contrast, if you only use combinators from `Reactive.Banana.Combinators`, then it is me who guarantees to you that no ordering issues will arise. It maybe somewhat disappointing that I do that by disallowing IO entirely, but alas, that's the best I can do. I don't think that there is a general way to deal with your situation (`s -> IO s`) in a deterministic manner.

Put differently: My proposed solution is not any more deterministic, but at least this fact is made explicit by requiring functions from `Reactive.Banana.Frameworks`.

That said, the `reactimate` are executed in "declaration order", which means that within the `Moment` monad, a call to `reactimate` that comes before a second call to `reactimate` will also have its IO actions executed before the IO actions of the second one. That gives you at least a small bit of predictability.

**Comment by lspitzner** [comment]
I see, thanks for all that information.
