### ISSUE TITLE
Building a new binding for slack rtm API

### ISSUE THREAD

**Issue by mathk** [HeinrichApfelmus/reactive-banana#142]
Hi,

I would like to propose using reactive-banana for slack rtm.
Slack rtm is mostly even base and I would like see if that would be a good idea to use a FRP style for handle such events.

Let me know

**Comment by HeinrichApfelmus** [comment]
Using reactive-banana to deal with an event-based API seems sensible to me, though it might be overkill if the API is used only in a very simple manner. 

I'm not sure if the question also implied whether such a binding might become part of the reactive-banana repository. I have to decline this, because it seems fairly specialized to me, e.g. I don't use the Slack API myself. Of course, that does in no way preclude anyone from writing such a binding and publishing it on hackage.

**Comment by mathk** [comment]
Ok I have start to write a POC to see how far I can get.
There is one think I have difficulty to express with rective-banana. 
In Slack API you have Messages Event that come.
And I am not sure how to express that.
My ides was to transform Messages event into Behavior. Because bot would certainly need to react to Messages. 
I should create a new behavior each time a message enter the network but I am not sure if I can do that. Any advise ?

**Comment by HeinrichApfelmus** [comment]
It seems sensible to me to model incoming messages as an `Event Message`.

**Comment by mathk** [comment]
So you advise me to have those kind of event stream:

```
[ (t1, (Message id1 text1),
(t2, (Message id2 text2)
(t3, (Message id1 text3)
(t4, (Message id2 text2) ]
```

Now the idea is to wire some response to `(Message id1)` and `(Message id2)` and update the response if the message is is being updated (at t3 in the example.).

How would you model the response behaviour ?

**Comment by ocharles** [comment]
As this issue is over 5 years out of date, I'm going to close this. @mathk if you need more help with this project, please don't hesitate to reach out to us again!
