### ISSUE TITLE
Consider adding a `once` primitive

### ISSUE THREAD

**Issue by ocharles** [HeinrichApfelmus/reactive-banana#74]
We had a discussion about this over on [StackOverflow](https://stackoverflow.com/questions/27816012/performing-a-single-switch-in-reactive-banana/27878929?noredirect=1#comment44315088_27878929).

**Comment by HeinrichApfelmus** [comment]
To recap the problem: The combinator `once` has type and semantics

    once :: Event a -> Moment (Event a)
    once e= \start -> take 1 [(t,a) | (t,a) <- e, start <= t]

It retains the first occurrence when the event starts, but discards the rest.

In principle, it can be implement as follows:

    once e = do
        isFirst <- stepper True $ False <$ e
        return $ whenE isFirst e

However, this implementation is unsatisfactory, because the Event could be *garbage collected* after its first occurrence, because it will be equivalent to `never` later on.

In general, the idea is that Events can be garbage collected if:

1. They have no observable effect.
2. They cannot have occurrences anymore.

The `once` combinator certainly satisfies the second criterion, but the implementation given does not allow for garbage collection, because `filterE` cannot "prove" to the compiler that the event may indeed never fire again.

I cannot find a way to express this in terms of dynamic event switching either. It seems to be necessary to implement this as a new primitive.

**Comment by HeinrichApfelmus** [comment]
This needs significantly more thought than I thought. At the moment, my plan is to release version 1.0 without this combinator and leave the issue open for later.

**Comment by ocharles** [comment]
I just found another bit of code that seems to require `once`. This code builds a command line interface for doing data entry. The idea is we can construct data by using a suitable applicative functor that prompts the user for the individual function arguments. As we provide arguments, we gradually apply the entire function. This can be done by switching between the arguments. Crucially, we only want the switching to go "forward", so we use `once` to ensure once we've provided an argument, we only consider subsequent arguments.

Here's a full example. I need to do a little more work on this to allow for the prompt to run multiple times, but hopefully this helps provide a little more motivation about this combinator.

```haskell
module Main where

import Control.Monad
import Reactive.Banana
import Reactive.Banana.Frameworks
import Text.Read

main :: IO ()
main =
  do (stdinAh,dispatchLine) <- newAddHandler
     compile (do stdin <- fromAddHandler stdinAh
                 runPrompt ((,) <$> name <*> age) stdin >>=
                   reactimate . fmap print) >>=
       actuate
     forever (getLine >>= dispatchLine)

newtype Prompt a =
  Prompt {runPrompt :: Event String -> MomentIO (Event a)}

instance Functor Prompt where
  fmap f (Prompt p) =
    Prompt (\stdin ->
              fmap (fmap f)
                   (p stdin))

instance Applicative Prompt where
  pure _ = Prompt (\_ -> return never)
  Prompt l <*> Prompt r =
    Prompt $
    \stdin ->
      do doneL <- l stdin >>= once
         execute (fmap (\f ->
                          do doneR <- r stdin >>= once
                             return (fmap f doneR))
                       doneL) >>=
           switchE

once e =
  do isFirst <- stepper True (False <$ e)
     return (whenE isFirst e)

name :: Prompt String
name =
  Prompt $
  \stdin ->
    do liftIO (putStrLn "Name: ")
       return stdin

age :: Prompt Int
age =
  Prompt $
  \stdin ->
    do liftIO (putStrLn "Age: ")
       return (filterJust (fmap readMaybe stdin))
```

**Comment by mitchellwrosen** [comment]
I think `dropE` is another motivating example. Here are two ways I came up with implementing it:

```haskell
-- first-order
dropE :: Int -> Event a -> Moment (Event a)
dropE n event = do
  count <- accumB 0 ((+1) <$ event)
  pure (whenE ((>= n) <$> count) event)

-- higher-order
dropE :: Int -> Event a -> Moment (Event a)
dropE n event = do
  count <- accumE 0 ((+1) <$ event)
  switchE (event <$ filterE (== n) count)
```

I believe in both cases (`reactive-banana-1.1`), we keep performing some unwanted computation forever, when we'd really like to stop counting events after we've dropped the given number. Could this be solved with `once`?

```haskell
-- higher-order
dropE :: Int -> Event a -> Moment (Event a)
dropE n event = do
  count <- accumE 0 ((+1) <$ event)
  switchE (event <$ once (filterE (== n) count))
```

**Comment by mitchellwrosen** [comment]
Just curious, are there any other updates on the plans for this combinator, whether it still makes sense, if it's even necessary, etc. that didn't make it into this issue tracker?

**Comment by HeinrichApfelmus** [comment]
Not from me at the moment. The `once` combinator seems necessary in some circumstances and therefore worth considering for implementation.

The thing I do not understand about `once` is how general it is, i.e. whether there are other combinators with similar properties, but which cannot be implemented in terms of `once`.

**Comment by ChristopherKing42** [comment]
It appears that all that is necessary is to create a version of `switchE` that allows you specify an initial event value. That is, you need a function `switchE' :: Event a -> Event (Event a) -> Moment (Event a)`. This can actually replace `switchE` as a primitive, since `switchE = switchE' never`.

Then

```
once = mdo
    e1 <- switchE' e $ (const never) <$ e1
    return e1
```

Theoretically `e` should be garbage collected as long as `switchE'` realizes it can garbage collect its initial event after switching. If you make it even smarter, `e1` would realize that after the it fires that it will only ever fire again if `never` or `e1` fires. Since it's "dependency graph" contains no primitive events, it realizes that it will never fire again, and can essentially be replaced by `never`. Then any other events that previously depended on it can ignore it, and the event might be able to be garbage collected as well (as long as Haskell itself no longer has any other references to it).

**Comment by ocharles** [comment]
Now that we have the new `switchE` we can define `once`. Should we? I'd also be happy to just close this issue for now, as it can be defined by users if they want.

**Comment by HeinrichApfelmus** [comment]
> Now that we have the new switchE we can define `once`. Should we?

Yes, I believe we should — its garbage collection properties are somewhat useful, and it's the combination of primitives to be used is not obvious. 🤔 Probably in the section on derived combinators.

I'd favor the implementation in terms of `switchE` for now, though it seems a bit overkill; we can improve it later.

**Comment by ocharles** [comment]
Oh, are you saying that `once` can still not suitably be defined using `switchE`? I thought that `switchE e (never <$ e)` would have the correct GC properties. I'll look into adding this to `Reactive.Banana.Combinators` tomorrow!

**Comment by HeinrichApfelmus** [comment]
> Oh, are you saying that once can still not suitably be defined using switchE? I thought that switchE e (never <$ e) would have the correct GC properties. 

Ah, I was not trying to say this — just that using `switchE` is "overkill" in the sense that an implementation of `once` in terms of `Pulse` and `Latch` probably uses fewer primitives. However, we do not need to care about this overkill for the time being.

I think that the suggestion by ChristopherKing42,

```
once e = mdo
    e1 <- switchE' e $ (const never) <$ e1
    return e1
```

has the correct garbage collection properties. The event `e` will be switched away and can then be garbage collected. The event `e1` will be kept in memory, but it only keeps a reference to itself and depends on `never`, so it can be garbage collected (at least in principle, I'm not entirely confident that the implementation is very good at garbage collection, yet).

**Comment by ocharles** [comment]
Ah, that makes sense. Ok, `once` PR with that definition is on its way!
