### ISSUE TITLE
Why AnyMoment?

### ISSUE THREAD

**Issue by fread2281** [HeinrichApfelmus/reactive-banana#93]
Why `AnyMoment` as opposed to using forall in the types of the dynamic switching functions?

**Comment by HeinrichApfelmus** [comment]
It's true that `AnyMoment` just wraps a universally quantified type. However, this is necessary because GHC does not support impredicative polymorphism very well.

**Comment by ocharles** [comment]
To clarify, "impredicative polymorphism" is the idea that you can return types with quantification in them. For example,

```haskell
fooble :: Int -> Maybe (forall a. Show a => a)
```

is impredicative polymorphism. This turns out to be really hard to build decent type inference around, so it's really pretty horrible to try and work with this in Haskell. As a "hack", it often comes out nicer if we reify this:

```haskell
data Showable where
  Showable :: Show a => a -> Showable

usableFooble :: Int -> Maybe Showable
```

**Comment by HeinrichApfelmus** [comment]
The `AnyMoment` type has been removed in the `monadic-api` branch.
